modern_data_pipeline:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', 'pipeline.duckdb') }}"
      threads: 4

    prod:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', 'pipeline.duckdb') }}"
      threads: 4